### PR TITLE
Fix #233

### LINKED ISSUE #233: Checking for changed order in JSON with NSOrderedSet
Hi there,
I'm not sure whether this is a bug or if this might be solvable through configuration.

As far as I know arrays in JSON are ordered and CoreData allows ordering as well using `NSOrderedSet`. So in my opinion Sync should change the data when the order of an array has changed, which does not happen at the moment.

I [forked SyncAppNetDemo](https://github.com/dersvenhesse/SyncAppNetDemo) and built a many-to-many relationship with humans and cars to illustrate the issue. Start the app and let Sync do its job. Then change the order of the cars in `global.json` and start the app again. Now I think the ordering in CoreData should be updated and the `changeNotification` for updated objects triggered.

How do you guys think this should be handled?

### PR DESCRIPTION
**Pull request by 3lvis**
So far we just have a test case to fix this. If you have any suggestions in how to improve it, please let us know.

### CODE REVIEW

**Comment by dersvenhesse** [comment]
@3lvis 
I do think I solved the problem for syncing lists with ids. Do you mind taking a look at that and maybe help me out by finding a similar solution for `sync_toManyRelationship`? Thanks.

**Comment by 3lvis** [comment]
Hi @dersvenhesse, I'm quite busy this week. I'll put some time to look into it this Monday. I hope this won't cause troubles for you.

**Comment by dersvenhesse** [comment]
@3lvis works for me. Thanks a lot!

**Comment by 3lvis** [comment]
@dersvenhesse nice solution!

**Comment by 3lvis** [comment]
👏

**Comment by 3lvis** [comment]
Let's merge this and make a separate issue for `sync_toManyRelationship`

**Pull request merged**
