### PR TITLE
[WIP] Add two way sync

### PR DESCRIPTION
**Pull request by FrancisBehnen**
This PR depends on https://github.com/3lvis/DATAFilter/pull/31. It adds support to return local insertions and deletions, for users that have two way communication with their remote storage.

All feedback is welcome!

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
I have not used this in a real application yet, but I have a pretty good idea of how I'm going to use it (See use case in DATAFilter PR). If you have any suggestion, feel free to comment.

**Comment by gerrypower** [comment]
This would be an excellent addition - two way sync open source is rare.

**Comment by Fr4nc3sc0NL** [comment]
Hi Gerry, thanks for your comment! Do you have an idea how we can implement this without adding more requisites for users? Elvis likes the idea too, but is hesitant to pull this implementation into the library since it adds the need for a very specific attribute in the entity you want to have two way sync with. If you have any ideas on how to overcome this please comment in the [DATAFilter pull request](https://github.com/3lvis/DATAFilter/pull/31)

**Comment by FrancisBehnen** [comment]
Hi Gerry, thanks for your comment! Do you have an idea how we can implement this without adding more requisites for users? Elvis likes the idea too, but is hesitant to pull this implementation into the library since it adds the need for a very specific attribute in the entity you want to have two way sync with. If you have any ideas on how to overcome this please comment in the [DATAFilter pull request](https://github.com/3lvis/DATAFilter/pull/31)

**Comment by 3lvis** [comment]
Hi @FrancisBehnen,

I'm sorry this took so long. I finally went through the article. In my current app I have a similar requirement and I'm using Sync.

Basically every local element has a `needsUpload` attribute, this is a Boolean. When I call Sync, I provide the predicate: `NSPredicate(format: "needsUpload == %@", false)`, meaning, only sync items where the needsUpload item is false.

Later I will use a NSFetchRequest to fetch all the items with `needsUpload == true` and send them to the backend one by one. Once one upload is completed, the local item receives an remote ID, and the `needsUpload` attribute is set to `false`.

**Comment by 3lvis** [comment]
Gonna close this since, it could be achieved by using the predicate to skip attributes that should be ignored from the Sync process.

**Pull request closed without merging**
